PACKRAT_CACHE = '/var/cache/syna/packrat/'
WORKSPACE = '/home/pi/jupyter/workspace/'
WORKSPACE_CACHE = WORKSPACE + 'packrat/'
WORKSPACE_TEMP_HEX = WORKSPACE_CACHE + 'temp.hex'
WORKSPACE_CACHE_FOLDER = WORKSPACE + '.cache/'
WORKSPACE_TEMP_FILE = WORKSPACE_CACHE_FOLDER + 'temp.cache'