PACKRAT_CACHE = '/var/cache/syna/packrat/'
WORKSPACE = '/home/pi/jupyter/workspace/'
WORKSPACE_PACKRAT_DIR = WORKSPACE + 'packrat/'
WORKSPACE_CACHE_DIR = WORKSPACE + '.cache/'
WORKSPACE_TEMP_FILE = WORKSPACE_CACHE_DIR + 'temp.cache'